# Generated by Django 5.1.1 on 2024-09-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
